### ISSUE TITLE
connection problem with PostgreSQL

### ISSUE THREAD

**Issue by MichaelDBA** [danap/ajqvue#1]
I am not able to setup the connection to PostgreSQL.  It's basically how to make the driver, org.postgresql.Driver to where I downloaded the postgresql jdbc jar file, postgresql-42.1.4.jar.

I know how to run it as a jdbc program and got it to work, but can't figure out how to supply parameters to ajqvue.

**Comment by danap** [comment]
Hello Michael,

That is correct, since I try to keep the download to a minimum
size I do not include all the various JDBC drivers for Ajquve.

1. Go to the PostgresSQL website and download the postgresql-42.1.4.jar,
   assuming the workstation has Java 8, which from the error
   message it does, jre1.8.0_144.

   https://jdbc.postgresql.org/download.html

2. Locate the Java installation directory to install the Jar file
   to the lib\ext\ directory.

   Ajqvue tries to guess the Java location of the Java installation
   based on system variables. In this case a hint to its location
   is c:\Program Files\Java\jre1.8_144.

3. Copy postgresql-42.1.4.jar to the Java directory from 2.

   Looks like: c:\Program Files\Java\jre1.8.0_144\lib\ext\

Hope this helps. Additional information can be obtained from
the manual in the docs directory and videos on the website,

http://ajqvue.com/documentation.html
