### ISSUE TITLE
Can I help you in the Hungarian translation?

### ISSUE THREAD

**Issue by csanyipal** [danap/ajqvue#3]
Hello,

I just start to using Ajqvue and it is beautiful.
I am using it in Hungarian language.
I see some strange translations for a few words.

Can I help you in the Hungarian translation?

Best, Pali

**Comment by danap** [comment]
Hello Pali,

Locale, translations are essentially done through Google Translate, translate.google.com.

In the project directory is a locale, directory. The Ajqvue_en_US.html file is fed to Google
translate. The translation is copied from the browser display then pasted into the spreadsheet
AjqvueBundle_blank.ods column B. The spreadsheet is then exported in CSV format with
UTF-16. That file is then opened with JEdit to remove the quotes, commas to become the
AjqvueBundle_xx_XX.properties file. So for Hungarian, AjqvueBundle_hu_HU.properties.

This is the process I use to create the properties files in that locale directory. It is efficient
and allows me to perform in translation for almost any language, but of course relies on
Google Translation. Each plugin must also go through the same process. Around 30 minutes
for each project.

Since Ajqvue is a stable project, started in 2005, I do not have changes in locale information
often. I suppose if you would like to help in the Hungarian translation then the file AjqvueBundle
hu_HU.properties file could be edited directly and you could submit a pull and I will update.
JEdit is one of the only text editors that I have found that allow the buffer to set to a specific
character encoding. IT MUST BE in UTF-16 ENCODING!

If I have to to do a update of the locale information I could track those changes and compare
to Google's translation to check for discrepancies.

I have added this base comment on translation to the locale directory this morning,
Ajqvue-Translations_README.txt.

danap.

**Comment by csanyipal** [comment]
Hello Dana,

it seems to me that that I do not know how to submit a pull. I tried to click on the 'New Pull Request' button, but this guides me to the 'Compare changes' page where I can't pull any request.

Sorry.

How can I pull request here?

Pali

**Comment by danap** [comment]
On Tue, August 7, 2018 1:19 pm, Csányi Pál wrote:
> Hello Dana,
>
> it seems to me that that I do not know how to submit a pull. I tried to
> click on the 'New Pull Request' button, but this guides me to the
> 'Compare changes' page where I can't pull any request.
>
> Sorry.
> How can I pull request here?
>
> Pali

Hello Pali,

Since I do not do these often I will have to review, but
it seems the pull is there.

Github has documentation on many of these subjects.
https://help.github.com/
https://help.github.com/articles/fork-a-repo/

Now, I have the changed AjqvueBundle_hu_HU.properties file.
Since there are many changes I would like to review, then
will comment with the pull request on GitHub.

In the meantime, as you probably already know you can
substitue that new translation in your locale directory of
Ajqvue to use now. I have already done so and it has no
problems with the character encoding, looks good!

Ajqvue v2.0 has been release this week.
http://ajqvue.com

danap.

**Comment by csanyipal** [comment]
Hello Dana,
I have managed to use pull request finally, so the new AjqvueBundle_hu_HU.properties file is there for you.
Pali
