### ISSUE TITLE
Will Ajqvue support some additional features?

### ISSUE THREAD

**Issue by csanyipal** [danap/ajqvue#7]
Hello Dana,

I wish to have in Ajqvue support for foreign keys - that is, to graphically can construct a foreign key, and for graphically represented database structures like it SchemaCrawler does, namely the Diagramming feature.
Moreover, when I start Ajqvue, for me it is difficult to open an SQLite database because there is no File  Browser to select a SQLite database file in the filesystem out there. I wish to can select a SQLite database file in a File Browser at Ajqvue startup.

When it will be if it will be at all such features in Ajqvue?

Best, Pali

**Comment by danap** [comment]
On Tue, August 28, 2018 4:05 am, Csányi Pál wrote:
> Hello Dana,
> I wish to have in Ajqvue support for foreign keys - that is, to
> graphically can construct a foreign key, and for graphically represented
> database structures like it SchemaCrawler does, namely the Diagramming
> feature.

The plugin QueryBuilder is based on a project on Sourceforge. I have been
meaning to review the code, but have not done this for over a year. When
I do I ususally will contribute any fixes between QueryBuilder and SQLeo.

I would have to review SchemaCrawler to fully understand the Diagramming
feature to see if I could implement in QueryBuilder. So will put on the
task list to review for consideration.

https://sourceforge.net/projects/sqleo/

> Moreover, when I start Ajqvue, for me it is difficult to open an
> SQLite database because there is no File  Browser to select a SQLite
> database file in the filesystem out there. I wish to can select a SQLite
> database file in a File Browser at Ajqvue startup.
> 
> When it will be if it will be at all such features in Ajqvue?
> Best, Pali

I will put a File Browser feature on the task list for selecting files
for a local database. I think this will be easy and will include in the
next release.

The next release will be soon, because I'm just now finishing up work
on a DB_To_FileMemoryDB plugin that works with SQLite. It will allow
users to use a SQL Query to transfer data to a local memory or file
database.

danap.

**Comment by csanyipal** [comment]
Thank you very much for your work!!

Best, Pali

**Comment by danap** [comment]
Hello,

I have separated this into two issues.

#8 Support for Foreign Keys
#9 StandardParametersPanel File Browser for DB

danap
